import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const target = resolve(root, "scripts/validate.mjs");
const args = process.argv.slice(2);
if (args.length > 1 || (args.length === 1 && args[0] !== "--check"))
  throw new Error("Usage: bun scripts/build.mjs [--check]");
const result = await Bun.build({
  entrypoints: [resolve(root, "src/cli.ts")],
  root,
  target: "node",
  format: "esm",
  banner: "// Generated by bun run build; edit src/, not this file.",
});
if (!result.success || result.outputs.length !== 1)
  throw new Error(`Build failed: ${result.logs.join("\n")}`);
const output = await result.outputs[0].text();
if (args[0] === "--check") {
  if ((await readFile(target, "utf8")) !== output)
    throw new Error("Stale distribution: run bun run build.");
  process.stdout.write("Distribution matches source.\n");
} else {
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, output);
  process.stdout.write("Generated scripts/validate.mjs.\n");
}
