// Generated by bun run build; edit src/, not this file.

// src/validate.ts
import { readFile, realpath, stat } from "node:fs/promises";
import { dirname, resolve } from "node:path";

// src/schema.ts
var artifactKinds = ["roadmap", "mission", "packet", "state", "result"];
var transitions = {
  draft: ["ready", "cancelled", "superseded"],
  ready: ["draft", "executing", "cancelled", "superseded"],
  executing: ["validating", "failed", "cancelled", "superseded"],
  validating: ["executing", "completed", "failed", "cancelled", "superseded"],
  completed: [],
  failed: [],
  cancelled: [],
  superseded: []
};
var outcomes = ["accepted", "correction_required", "needs_decision", "blocked"];
function isStatus(value) {
  return typeof value === "string" && Object.hasOwn(transitions, value);
}
function isInterruption(value) {
  return value === null || isObject(value) && ["needs_decision", "blocked"].includes(value.kind) && isText(value.reason);
}
function isCommit(value) {
  return typeof value === "string" && /^(?:[0-9a-f]{40}|[0-9a-f]{64})$/.test(value);
}
function isReference(value, kind) {
  return isObject(value) && isText(value.path) && !/^[a-z][a-z0-9+.-]*:/i.test(value.path) && (kind === undefined || value.kind === kind) && (value.kind === "document" || value.kind === "evidence" || artifactKinds.includes(value.kind) && isText(value.id) && isRevision(value.revision));
}
function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function isText(value) {
  return typeof value === "string" && value.trim().length > 0;
}
function isRevision(value) {
  return Number.isSafeInteger(value) && value > 0;
}
function schemaErrors(value) {
  if (!isObject(value))
    return ["Expected an object."];
  const errors = [];
  if (value.schemaVersion !== 1)
    errors.push("schemaVersion must be 1.");
  if (!artifactKinds.includes(value.kind))
    errors.push("Unsupported artifact kind.");
  if (!isText(value.id))
    errors.push("id must be a nonempty string.");
  if (!isRevision(value.revision))
    errors.push("revision must be a positive safe integer.");
  if (value.kind === "mission" && !isText(value.repository))
    errors.push("repository must be a local directory path.");
  if (value.refs !== undefined && (!Array.isArray(value.refs) || !value.refs.every((ref) => isReference(ref)))) {
    errors.push("refs must contain typed local references; workflow references require id and revision.");
  }
  if (["packet", "state", "result"].includes(value.kind) && !isReference(value.mission, "mission"))
    errors.push("mission must reference an exact Mission Contract revision.");
  if (value.kind === "packet" && !isCommit(value.baseCommit))
    errors.push("baseCommit must be a full Git object id.");
  if (value.kind === "state") {
    if (!isStatus(value.status))
      errors.push("Unsupported mission status.");
    if (!isInterruption(value.interruption))
      errors.push("interruption must be null or a blocked/needs_decision record with reason.");
    if (!isText(value.history))
      errors.push("history must name the local JSONL journal.");
    if (!isRevision(value.lastSequence))
      errors.push("lastSequence must be a positive safe integer.");
    if (value.currentPacket !== null && !isReference(value.currentPacket, "packet"))
      errors.push("currentPacket must be null or an exact packet reference.");
    if (!Array.isArray(value.attempts) || !value.attempts.every((a) => isObject(a) && isReference(a.packet, "packet") && (a.result === null || isReference(a.result, "result"))))
      errors.push("attempts must contain packet and nullable result references.");
    if (!Array.isArray(value.checkpoints) || !value.checkpoints.every((c) => isObject(c) && isReference(c.packet, "packet") && isReference(c.result, "result") && isCommit(c.commit) && isText(c.actor)))
      errors.push("checkpoints require packet, result, full commit and accepting actor.");
    if (!Array.isArray(value.evidence) || !value.evidence.every((e) => isReference(e, "evidence")))
      errors.push("evidence must contain local evidence references.");
    if (value.validation !== null && !isReference(value.validation, "result"))
      errors.push("validation must be null or a result reference.");
  }
  if (value.kind === "result") {
    if (!["packet", "mission"].includes(value.scope))
      errors.push("scope must be packet or mission.");
    if (value.scope === "packet" ? !isReference(value.packet, "packet") : value.packet !== null)
      errors.push("packet is required for packet results and must be null for mission results.");
    if (!isText(value.actor) || !isText(value.summary))
      errors.push("actor and summary must be nonempty strings.");
    if (!Array.isArray(value.implementers) || value.implementers.length === 0 || !value.implementers.every(isText))
      errors.push("implementers must list nonempty actor identities.");
    if (typeof value.freshContext !== "boolean")
      errors.push("freshContext must be an explicit boolean.");
    if (!outcomes.includes(value.outcome))
      errors.push("Unsupported attempt outcome.");
    if (!Array.isArray(value.evidence) || !value.evidence.every((e) => isReference(e, "evidence")))
      errors.push("evidence must contain local evidence references.");
  }
  return errors;
}
function eventErrors(value) {
  if (!isObject(value))
    return ["Expected an event object."];
  const errors = [];
  if (value.schemaVersion !== 1 || value.kind !== "event")
    errors.push("Expected a V1 event.");
  if (!isRevision(value.sequence) || !isRevision(value.stateRevision))
    errors.push("sequence and stateRevision must be positive safe integers.");
  if (!isText(value.at) || !/^\d{4}-\d{2}-\d{2}T.*(?:Z|[+-]\d{2}:\d{2})$/.test(value.at) || !Number.isFinite(Date.parse(value.at)))
    errors.push("at must be an ISO timestamp with timezone.");
  if (!isText(value.actor) || !isText(value.reason))
    errors.push("actor and reason must be nonempty strings.");
  if (!isReference(value.mission, "mission"))
    errors.push("mission must reference an exact contract revision.");
  if (!isStatus(value.status) || !isInterruption(value.interruption))
    errors.push("Invalid status or interruption.");
  if (!Array.isArray(value.evidence) || !value.evidence.every((e) => isReference(e, "evidence")))
    errors.push("evidence must contain local evidence references.");
  return errors;
}

// src/validate.ts
async function validateArtifact(path) {
  const issues = [];
  const cache = new Map;
  let readError = false;
  const issue = (path2, rule, message) => {
    issues.push({ path: path2, rule, message });
  };
  function sameReference(aFile, a, bFile, b) {
    return a.kind === b.kind && a.id === b.id && a.revision === b.revision && resolve(dirname(aFile), a.path) === resolve(dirname(bFile), b.path);
  }
  function sameInterruption(a, b) {
    if (a === null || b === null)
      return a === b;
    return a.kind === b.kind && a.reason === b.reason;
  }
  async function history(file, text) {
    const lines = text.trimEnd().split(/\r?\n/);
    if (!text.trim()) {
      issue(file, "history-empty", "History must contain at least the initial draft event.");
      return;
    }
    let previous;
    for (let index = 0;index < lines.length; index++) {
      let value;
      try {
        value = JSON.parse(lines[index]);
      } catch {
        issue(file, "parse", `Invalid JSONL event on line ${index + 1}.`);
        return;
      }
      const errors = eventErrors(value);
      if (errors.length) {
        for (const message of errors)
          issue(file, "schema", `Line ${index + 1}: ${message}`);
        return;
      }
      const event = value;
      if (event.sequence !== index + 1)
        issue(file, "history-sequence", `Expected sequence ${index + 1} on line ${index + 1}.`);
      if (!previous && event.status !== "draft")
        issue(file, "history-transition", "History must start in draft.");
      if (previous) {
        const from = previous.status;
        if (!(transitions[from].includes(event.status) || from === event.status && transitions[from].length > 0))
          issue(file, "history-transition", `Invalid phase transition on line ${index + 1}.`);
        if (event.stateRevision <= previous.stateRevision)
          issue(file, "history-sequence", "stateRevision must increase with each event.");
        if (event.mission.id !== previous.mission.id || event.mission.revision < previous.mission.revision)
          issue(file, "history-mission", "History must keep one mission identity without decreasing its revision.");
      }
      await reference(file, event.mission);
      for (const ref of event.evidence)
        await reference(file, ref);
      previous = event;
    }
    return previous;
  }
  async function reference(owner, ref) {
    const target = resolve(dirname(owner), ref.path);
    try {
      if (!(await stat(target)).isFile())
        throw new Error("Not a file");
    } catch {
      issue(owner, "reference-missing", `Referenced file is unavailable: ${ref.path}`);
      return;
    }
    if (ref.kind === "document" || ref.kind === "evidence")
      return;
    const data = await visit(target);
    if (data && (data.kind !== ref.kind || data.id !== ref.id || data.revision !== ref.revision)) {
      issue(owner, "reference-identity", `Referenced kind, id or revision does not match: ${ref.path}`);
      return;
    }
    return data;
  }
  async function visit(file, asHistory = false) {
    let key;
    let text;
    try {
      key = await realpath(file);
      if (cache.has(key)) {
        const cached = cache.get(key);
        if (asHistory && cached && cached.kind !== "event") {
          issue(file, "history-format", "history must reference a JSONL event journal, not another artifact.");
          return;
        }
        return cached;
      }
      if (!(await stat(key)).isFile())
        throw new Error("Not a regular file");
      text = await readFile(key, "utf8");
    } catch {
      issue(file, "read", "Cannot read artifact.");
      readError = true;
      return;
    }
    cache.set(key, undefined);
    file = key;
    if (asHistory || file.endsWith(".jsonl")) {
      const last = await history(file, text);
      cache.set(key, last);
      return last;
    }
    let parsed;
    const metadata = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/.exec(text);
    try {
      parsed = JSON.parse(metadata ? metadata[1] : text);
    } catch {
      issue(file, "parse", "Expected strict JSON or JSON frontmatter.");
      return;
    }
    const errors = schemaErrors(parsed);
    if (errors.length) {
      for (const message of errors)
        issue(file, "schema", message);
      return;
    }
    const data = parsed;
    const markdown = ["roadmap", "mission", "packet"].includes(data.kind);
    if (markdown !== Boolean(metadata) || metadata && !text.slice(metadata[0].length).trim()) {
      issue(file, "format", "Contracts and packets require JSON frontmatter with prose; state and results require plain JSON.");
      return;
    }
    cache.set(key, data);
    if (data.kind === "mission") {
      try {
        if (!(await stat(resolve(dirname(file), data.repository))).isDirectory())
          throw new Error("Not a directory");
      } catch {
        issue(file, "repository", "repository must resolve to an existing local directory.");
      }
    }
    for (const ref of data.refs ?? [])
      await reference(file, ref);
    if (data.mission)
      await reference(file, data.mission);
    if (data.kind === "result") {
      if (data.packet) {
        const ref = data.packet;
        const packet = await reference(file, ref);
        if (packet && !sameReference(file, data.mission, resolve(dirname(file), ref.path), packet.mission))
          issue(file, "result-mission", "Result and packet must refer to the same mission revision.");
      }
      for (const ref of data.evidence)
        await reference(file, ref);
      if (data.outcome === "accepted") {
        if (data.implementers.includes(data.actor))
          issue(file, "independent-acceptance", "An implementer cannot accept their own result.");
        if (!data.evidence.length)
          issue(file, "acceptance-evidence", "Acceptance must reference evidence.");
        if (data.scope === "mission" && data.freshContext !== true)
          issue(file, "independent-validation", "Mission acceptance requires a fresh validation context.");
      }
    }
    if (data.kind === "state") {
      const mission = data.mission;
      if (data.id !== mission.id)
        issue(file, "mission-identity", "State id must match its mission id.");
      const attempts = data.attempts;
      for (const attempt of attempts) {
        const packet = await reference(file, attempt.packet);
        if (packet && packet.mission.id !== data.id)
          issue(file, "mission-identity", "Every attempt must belong to this mission.");
        if (attempt.result) {
          const result = await reference(file, attempt.result);
          if (result && (result.scope !== "packet" || !sameReference(file, attempt.packet, resolve(dirname(file), attempt.result.path), result.packet)))
            issue(file, "attempt-result", "Attempt result must address its packet.");
        }
      }
      if (data.currentPacket) {
        const active = data.currentPacket;
        const packet = await reference(file, active);
        if (!attempts.some((a) => sameReference(file, a.packet, file, active)))
          issue(file, "active-attempt", "currentPacket must belong to attempts.");
        if (packet && !sameReference(file, mission, resolve(dirname(file), active.path), packet.mission))
          issue(file, "active-revision", "The active packet does not reference the active mission revision.");
      }
      for (const ref of data.evidence)
        await reference(file, ref);
      for (const checkpoint of data.checkpoints) {
        await reference(file, checkpoint.packet);
        const result = await reference(file, checkpoint.result);
        if (!attempts.some((a) => sameReference(file, a.packet, file, checkpoint.packet) && a.result && sameReference(file, a.result, file, checkpoint.result)) || result && (result.scope !== "packet" || result.outcome !== "accepted" || !sameReference(file, checkpoint.packet, resolve(dirname(file), checkpoint.result.path), result.packet) || result.implementers.includes(checkpoint.actor)))
          issue(file, "checkpoint-acceptance", "Checkpoint must cite a registered accepted packet result and a non-implementing accepting actor.");
      }
      const validation = data.validation ? await reference(file, data.validation) : undefined;
      if (validation && (validation.scope !== "mission" || !sameReference(file, mission, resolve(dirname(file), data.validation.path), validation.mission)))
        issue(file, "validation-revision", "Mission validation must address the active mission revision.");
      if (data.status === "completed") {
        if (validation?.scope !== "mission" || validation.outcome !== "accepted" || validation.freshContext !== true)
          issue(file, "completion-validation", "Completion requires an accepted independent mission result.");
        if (data.currentPacket !== null || data.interruption !== null || !attempts.length || attempts.some((a) => a.result === null))
          issue(file, "completion-pending", "Completion cannot retain an active packet, interruption or unresolved attempt, and requires an attempt history.");
      }
      const historyPath = resolve(dirname(file), data.history);
      const last = await visit(historyPath, true);
      if (last && (last.sequence !== data.lastSequence || last.stateRevision !== data.revision || last.status !== data.status || !sameInterruption(last.interruption, data.interruption) || !sameReference(file, mission, historyPath, last.mission)))
        issue(file, "history-state", "State must agree with the last event's sequence, state revision, mission, status and interruption.");
    }
    return data;
  }
  await visit(resolve(path));
  issues.sort((a, b) => a.path.localeCompare(b.path) || a.rule.localeCompare(b.rule) || a.message.localeCompare(b.message));
  return { valid: issues.length === 0, issues, exitCode: readError ? 2 : issues.length ? 1 : 0 };
}

// src/cli.ts
var args = process.argv.slice(2);
var usage = "Usage: node scripts/validate.mjs <artifact-path> [--json]";
var json = args.includes("--json");
var paths = args.filter((arg) => !arg.startsWith("--"));
function print(report) {
  if (json)
    process.stdout.write(`${JSON.stringify({ valid: report.valid, issues: report.issues })}
`);
  else if (report.valid)
    process.stdout.write(`Structurally valid; authorization and semantic acceptance are not verified.
`);
  else
    process.stdout.write(`${report.issues.map((i) => `${i.path}: ${i.rule}: ${i.message}`).join(`
`)}
`);
  process.exitCode = report.exitCode;
}
if (args.length === 1 && args[0] === "--help") {
  process.stdout.write(`${usage}
`);
} else if (paths.length !== 1 || args.some((arg) => arg.startsWith("--") && arg !== "--json") || args.filter((arg) => arg === "--json").length > 1) {
  print({
    valid: false,
    issues: [{ path: "<arguments>", rule: "usage", message: usage }],
    exitCode: 2
  });
} else {
  print(await validateArtifact(paths[0]));
}
